INSERT INTO tags (slug, name) VALUES
  ('environment', 'environment'),
  ('waste-management', 'waste management'),
  ('recycling', 'recycling'),
  ('transport', 'transport'),
  ('infrastructure', 'infrastructure'),
  ('urban-mobility', 'urban mobility'),
  ('water', 'water'),
  ('health', 'health'),
  ('sustainability', 'sustainability'),
  ('housing', 'housing'),
  ('affordability', 'affordability'),
  ('innovation', 'innovation'),
  ('agriculture', 'agriculture'),
  ('hydroponics', 'hydroponics'),
  ('urban-farming', 'urban farming'),
  ('climate', 'climate'),
  ('energy', 'energy'),
  ('forestry', 'forestry'),
  ('biodiversity', 'biodiversity'),
  ('drought', 'drought'),
  ('construction', 'construction'),

  -- Environment, climate, and resilience
  ('air-quality', 'air quality'),
  ('climate-adaptation', 'climate adaptation'),
  ('climate-justice', 'climate justice'),
  ('carbon-removal', 'carbon removal'),
  ('emissions', 'emissions'),
  ('extreme-heat', 'extreme heat'),
  ('flooding', 'flooding'),
  ('coastal-resilience', 'coastal resilience'),
  ('nature-based-solutions', 'nature-based solutions'),
  ('ecosystem-restoration', 'ecosystem restoration'),
  ('wetlands', 'wetlands'),
  ('soil-health', 'soil health'),
  ('conservation', 'conservation'),
  ('circular-economy', 'circular economy'),
  ('plastic-pollution', 'plastic pollution'),
  ('composting', 'composting'),
  ('repair', 'repair'),
  ('reuse', 'reuse'),
  ('zero-waste', 'zero waste'),
  ('environmental-monitoring', 'environmental monitoring'),
  ('environmental-justice', 'environmental justice'),
  ('wildfire', 'wildfire'),
  ('disaster-risk-reduction', 'disaster risk reduction'),
  ('resilience', 'resilience'),
  ('green-infrastructure', 'green infrastructure'),

  -- Energy and decarbonization
  ('renewable-energy', 'renewable energy'),
  ('solar-energy', 'solar energy'),
  ('wind-energy', 'wind energy'),
  ('energy-efficiency', 'energy efficiency'),
  ('building-retrofits', 'building retrofits'),
  ('district-heating', 'district heating'),
  ('heat-pumps', 'heat pumps'),
  ('energy-poverty', 'energy poverty'),
  ('community-energy', 'community energy'),
  ('electrification', 'electrification'),
  ('grid-resilience', 'grid resilience'),
  ('energy-storage', 'energy storage'),
  ('clean-cooking', 'clean cooking'),
  ('decarbonization', 'decarbonization'),

  -- Transport and mobility
  ('public-transit', 'public transit'),
  ('buses', 'buses'),
  ('rail', 'rail'),
  ('cycling', 'cycling'),
  ('walking', 'walking'),
  ('road-safety', 'road safety'),
  ('active-mobility', 'active mobility'),
  ('accessibility', 'accessibility'),
  ('electric-vehicles', 'electric vehicles'),
  ('charging-infrastructure', 'charging infrastructure'),
  ('freight', 'freight'),
  ('shared-mobility', 'shared mobility'),
  ('school-streets', 'school streets'),
  ('transit-equity', 'transit equity'),
  ('traffic-calming', 'traffic calming'),

  -- Housing and the built environment
  ('affordable-housing', 'affordable housing'),
  ('homelessness', 'homelessness'),
  ('tenant-rights', 'tenant rights'),
  ('zoning', 'zoning'),
  ('community-land-trusts', 'community land trusts'),
  ('modular-housing', 'modular housing'),
  ('building-materials', 'building materials'),
  ('adaptive-reuse', 'adaptive reuse'),
  ('public-space', 'public space'),
  ('urban-planning', 'urban planning'),
  ('land-use', 'land use'),
  ('universal-design', 'universal design'),
  ('green-buildings', 'green buildings'),
  ('informal-settlements', 'informal settlements'),
  ('neighborhood-revitalization', 'neighborhood revitalization'),

  -- Water and sanitation
  ('drinking-water', 'drinking water'),
  ('sanitation', 'sanitation'),
  ('wastewater', 'wastewater'),
  ('stormwater', 'stormwater'),
  ('rainwater-harvesting', 'rainwater harvesting'),
  ('groundwater', 'groundwater'),
  ('water-quality', 'water quality'),
  ('water-conservation', 'water conservation'),
  ('watershed-management', 'watershed management'),
  ('flood-management', 'flood management'),
  ('irrigation', 'irrigation'),
  ('rural-water', 'rural water'),
  ('water-affordability', 'water affordability'),

  -- Food and agriculture
  ('food-security', 'food security'),
  ('food-waste', 'food waste'),
  ('regenerative-agriculture', 'regenerative agriculture'),
  ('agroforestry', 'agroforestry'),
  ('community-gardens', 'community gardens'),
  ('local-food', 'local food'),
  ('school-meals', 'school meals'),
  ('nutrition', 'nutrition'),
  ('food-deserts', 'food deserts'),
  ('sustainable-fisheries', 'sustainable fisheries'),
  ('pollinators', 'pollinators'),
  ('seed-saving', 'seed saving'),
  ('soil-regeneration', 'soil regeneration'),
  ('cold-chain', 'cold chain'),
  ('food-redistribution', 'food redistribution'),

  -- Health, inclusion, and community
  ('public-health', 'public health'),
  ('mental-health', 'mental health'),
  ('maternal-health', 'maternal health'),
  ('disability-inclusion', 'disability inclusion'),
  ('aging', 'aging'),
  ('childcare', 'childcare'),
  ('youth', 'youth'),
  ('education', 'education'),
  ('digital-literacy', 'digital literacy'),
  ('social-isolation', 'social isolation'),
  ('community-care', 'community care'),
  ('healthcare-access', 'healthcare access'),
  ('air-pollution', 'air pollution'),
  ('heat-health', 'heat health'),
  ('gender-equity', 'gender equity'),
  ('refugee-support', 'refugee support'),
  ('indigenous-rights', 'indigenous rights'),
  ('poverty-reduction', 'poverty reduction'),

  -- Civic life, local economies, and technology
  ('civic-tech', 'civic tech'),
  ('open-data', 'open data'),
  ('participatory-budgeting', 'participatory budgeting'),
  ('community-organizing', 'community organizing'),
  ('local-government', 'local government'),
  ('public-policy', 'public policy'),
  ('cooperatives', 'cooperatives'),
  ('social-enterprise', 'social enterprise'),
  ('small-business', 'small business'),
  ('workforce-development', 'workforce development'),
  ('digital-inclusion', 'digital inclusion'),
  ('broadband', 'broadband'),
  ('open-source', 'open source'),
  ('citizen-science', 'citizen science')
ON CONFLICT DO NOTHING;
SELECT setval('tags_id_seq', (SELECT MAX(id) FROM tags));
