import type { H3Event } from 'h3'

// Cloudflare Email Sending binding shape — generated by `wrangler types`
// includes the real SendEmail types, but Nitro doesn't pull that into our
// server-side TS context, so we keep a minimal local type.
export interface SendEmailBinding {
  send(input: {
    to: string | string[]
    from: { email: string; name?: string }
    subject: string
    html: string
    text: string
    replyTo?: string
  }): Promise<{ messageId: string }>
}

// Scheduled tasks run without an h3 event, so they can't reach the binding
// via `event.context.cloudflare.env`. The `cloudflare:scheduled` hook (see
// server/plugins/hyperdrive.ts) stashes it here for the duration of the cron
// invocation instead. Bindings must not be reused across invocations on
// Workers, but each scheduled event overwrites the slot before any task runs,
// so the holder always points at the current invocation's binding.
let scheduledEmailBinding: SendEmailBinding | undefined

export function setScheduledEmailBinding(binding: SendEmailBinding | undefined): void {
  scheduledEmailBinding = binding
}

/**
 * Resolve the EMAIL binding for the current execution context: the request's
 * env when called with an event, the scheduled-invocation stash otherwise.
 */
export function resolveEmailBinding(event?: H3Event | null): SendEmailBinding | undefined {
  const ctx = event?.context as { cloudflare?: { env?: { EMAIL?: SendEmailBinding } } } | undefined
  return ctx?.cloudflare?.env?.EMAIL ?? scheduledEmailBinding
}
