export const issues = [
  {
    id: 1,
    title: 'Reduce household waste',
    description: 'Every year, millions of tons of waste end up in landfills. We need innovative solutions to reduce household waste and promote recycling.',
    author: 'Jane Doe',
    date: '2023-10-01',
    solutionCount: 523,
    subIssueCount: 212,
    commentCount: 45,
    sourceCount: 12,
    detailedDescription: 'Reducing household waste requires community engagement and sustainable practices. Innovative solutions such as improved recycling programs and waste management technologies are essential.',
    tags: ['environment', 'waste management', 'recycling'],
    sustainableDevelopmentGoals: [
      allSustainableDevelopmentGoals[12],
      allSustainableDevelopmentGoals[11],
    ],
  },
  {
    id: 2,
    title: 'Improve local public transport',
    description: 'Our public transport system is outdated and inefficient. We need ideas to enhance its reliability and accessibility.',
    author: 'John Smith',
    date: '2023-10-02',
    solutionCount: 312,
    subIssueCount: 145,
    commentCount: 32,
    sourceCount: 8,
    detailedDescription: 'Improving local public transport involves upgrading infrastructure, integrating technology, and increasing service frequency to meet community needs.',
    tags: ['transport', 'infrastructure', 'urban mobility'],
    sustainableDevelopmentGoals: [
      allSustainableDevelopmentGoals[11],
      allSustainableDevelopmentGoals[9],
    ],
  },
  {
    id: 3,
    title: 'Cheaper access to clean water',
    description: 'Access to clean water is a basic human right. We need to find ways to make it more affordable and accessible for everyone.',
    author: 'Alice Johnson',
    date: '2023-10-03',
    solutionCount: 198,
    subIssueCount: 87,
    commentCount: 15,
    sourceCount: 5,
    detailedDescription: 'This initiative focuses on providing affordable and reliable access to clean water through innovative filtration and distribution solutions.',
    tags: ['water', 'health', 'sustainability'],
    sustainableDevelopmentGoals: [
      allSustainableDevelopmentGoals[6],
      allSustainableDevelopmentGoals[3],
    ],
  },
  {
    id: 4,
    title: 'Affordable housing solutions',
    description: 'Housing prices are skyrocketing, making it difficult for many to find affordable places to live. We need creative solutions to this crisis.',
    author: 'Bob Brown',
    date: '2023-10-04',
    solutionCount: 410,
    subIssueCount: 175,
    commentCount: 67,
    sourceCount: 23,
    detailedDescription: 'Developing affordable housing solutions involves innovative design, efficient use of space, and sustainable construction to meet growing demands.',
    tags: ['housing', 'affordability', 'innovation'],
    sustainableDevelopmentGoals: [
      allSustainableDevelopmentGoals[11],
      allSustainableDevelopmentGoals[1],
    ],
  },
  {
    id: 5,
    title: 'Accessible hydroponics systems',
    description: 'Hydroponics can revolutionize urban farming, but current systems are too expensive for many. We need to develop affordable hydroponics solutions.',
    author: 'Charlie Green',
    date: '2023-10-05',
    solutionCount: 256,
    subIssueCount: 98,
    commentCount: 21,
    sourceCount: 9,
    detailedDescription: 'Accessible hydroponics systems can transform urban agriculture by reducing costs and increasing efficiency in growing food in limited spaces.',
    tags: ['agriculture', 'hydroponics', 'urban farming'],
    sustainableDevelopmentGoals: [
      allSustainableDevelopmentGoals[2],
      allSustainableDevelopmentGoals[11],
    ],
  },
  {
    id: 6,
    title: 'Curbing greenhouse gas emissions',
    description: 'Climate change is a pressing issue. We need innovative ideas to reduce greenhouse gas emissions in our community.',
    author: 'Diana White',
    date: '2023-10-06',
    solutionCount: 678,
    subIssueCount: 300,
    commentCount: 112,
    sourceCount: 34,
    detailedDescription: 'Innovative strategies to curb greenhouse gas emissions include transitioning to renewable energy sources and enhancing energy efficiency across industries.',
    tags: ['climate', 'sustainability', 'energy'],
    sustainableDevelopmentGoals: [
      allSustainableDevelopmentGoals[13],
      allSustainableDevelopmentGoals[7],
    ],
  },
]
